force-app/main/default/objects/ACSFCCP_HistoricalReportData__c/ACSFCCP_HistoricalReportData__c.object-meta.xml
<CustomObject>
    <description>Object to store historical data provided by Amazon Connect. Data stored in this object should be consumed by Salesforce Reports or Dashboards. The records are not meant to be managed by a user.</description>
    <label>Amazon Connect Historical Report Data</label>
    <nameField>
        <label>Amazon Connect Report Data Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amazon Connect Historical Report Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ACSFCCP_HistoricalReportData__c/fields/AC_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>AC_Object_Name__c</fullName>
    <label>AC Object Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACSFCCP_HistoricalReportData__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Amazon_Connect_Historical_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ACSFCCP_HistoricalReportData__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The AC artifact the report information is related to, either a Queue or an Agent.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
                <default>true</default>
                <label>Agent</label>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Amazon_Connect_Username__c.field-meta.xml
<CustomField>
    <fullName>Amazon_Connect_Username__c</fullName>
    <label>Amazon Connect Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ACSFCCP_UpdateReportAgentField.cls
public class ACSFCCP_UpdateReportAgentField {

  public static void linkToSalesforceUser(List<ACSFCCP_HistoricalReportData__c> records) {

    Map<String, Id> connectUsers = getConnectUsers();

    for (ACSFCCP_HistoricalReportData__c rec : records) {
      if (rec.Type__c == 'Agent' && connectUsers.containsKey(rec.AC_Object_Name__c)) {
        rec.Agent__c = connectUsers.get(rec.AC_Object_Name__c);
      }
    }
  }

  private static Map<String, Id> getConnectUsers() {
    List<User> connectUsers = [SELECT Amazon_Connect_Username__c FROM User WHERE Amazon_Connect_Username__c <> ''];

    Map<String, Id> result = new Map<String, Id>();
    for (User u : connectUsers) {
      result.put(u.Amazon_Connect_Username__c, u.Id);
    }
    return result;
  }
}